### ISSUE TITLE
How do you generate the mask  in transformer model and process text labels to "class_id" ?

### ISSUE THREAD

**Issue by DeepInSearch** [Bartzi/kiss#11]
As the project is reall huge, I'm not understand how you process the text labels ? Usually, in an attention based text recognitizer, there will be "[GO]" and "[EOS]" label and will be converted into "num 
 class_id". But I don't understand in the transformer model, how the code process the labels into "num class_id" and generate the mask as bellow :https://github.com/Bartzi/kiss/blob/25038d091cf4838b6aa51fc9865ed4dec9e5c673/text/transformer_recognizer.py#L23
 
and your code has some difference in generating the mask from 
https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/76762bb08225014fb3055a9d07f0043aba972d68/transformer/Models.py#L169

Do you have used "pad_idx", where can I find it ?  what's the difference in use "pad_idx" and not use ? I'm really confused with "pad_idx", "GO_idx", "EOS_idx", how do you process that part ?
I don't quite know how to process with it.  Could you give me some advice ?

**Comment by Bartzi** [comment]
Thanks for that question!

I'm using a "[GO]" token and an "[EOS]" token. The class id of both is defined in the [char_map](https://github.com/Bartzi/kiss/blob/master/train_utils/char-map-bos.json). See the metadata key.
The data loader processes each character (and with that also the [EOS] token) into a class id ([here](https://github.com/Bartzi/kiss/blob/master/common/datasets/text_recognition_image_dataset.py#L44)).
The BOS token is added to each sequence by the network itself during the forward pass ([for instance here](https://github.com/Bartzi/kiss/blob/master/text/transformer_recognizer.py#L43)).

The code you reference to, is the code that keeps the decoder from looking into the future and just focusing on the past outputs of the encoder for each time-step.

I based my implementation on [this bog post](http://nlp.seas.harvard.edu/2018/04/03/attention.html).

I hope that helps.

**Comment by DeepInSearch** [comment]
Is the 'bos_token' represent '[GO]', and 'blank_label' represent '[EOS]'. If I'm right, I think I have understood this part. Thank you ！

**Comment by Bartzi** [comment]
Yes, the bos (begin of sequence) token is the '[GO]' token and the blank label represents the eos token.
