### ISSUE TITLE
What is the inference speed of KISS ?

### ISSUE THREAD

**Issue by lamhoangtung** [Bartzi/kiss#12]
Hi. Thanks for the amazing work.

I was wondering that what is the inference speed of KISS on:
- A Single GPU
- CPU

Thanks for checking this out :P

**Comment by Bartzi** [comment]
Thanks for the question.

I just checked it on a machine with an Intel Core i9-7900X, with 64GB of RAM, 1 NVIDIA 1080Ti GPU, the images are read from an Samsung 850 Evo SSD, the system is running Arch Linux, with CUDA 10.2, we use Chainer 7.1.0, and Cupy 7.1.1:

- running on the GPU with a batch size of 1, we can reach 6 iterations per second, but with a batch size of 16, we can reach 64 iterations per second
- on the CPU things are naturally way slower :sweat_smile:, here we can reach around 1 iteration per second with a batch size of 1 and 0.1 iterations per second with a batch size of 16

**Comment by lamhoangtung** [comment]
Thanks for the quick response @Bartzi. The speed is very impressive.

I was wondering how big your test images is and how much text instance are there in each test sample ?

**Comment by Bartzi** [comment]
The images have a size of `200x64`. Each test image contains one cropped word (up to a length of 23 characters in the case of our best performing model), as it is common for scene text recognition benchmarks.

**Comment by lamhoangtung** [comment]
Still impressive. Thanks for the answer
