### ISSUE TITLE
what is gt.mat?

### ISSUE THREAD

**Issue by dikubab** [Bartzi/kiss#17]
I have both labels in gt texts and images of real-world data. How can I get the gt.mat or crop using crop_words_from_oxford.py

**Comment by Bartzi** [comment]
You only need `gt.mat` and `crop_words_from_oxford.py` if you want to evaluate the model on the [SynthText Dataset](https://www.robots.ox.ac.uk/~vgg/data/scenetext/).

However, it seems you already have annotations and images? What do you want to do? Run a trained model on your data and examine the result? Retrain the model?

**Comment by dikubab** [comment]
Thank you for your prompt response.
