### ISSUE TITLE
Training Text-Detection

### ISSUE THREAD

**Issue by deepseek** [Bartzi/kiss#4]
@Bartzi Thank you for  your hard work,

I can't seem to figure-out how to train text-detection on [icdar2015](https://rrc.cvc.uab.es/?ch=4&com=introduction).

**Comment by Bartzi** [comment]
ICDAR2015 is only meant for evaluation, as this dataset does not contain enough data for training a deep model. You should train the model on synthetic datasets, like MJSynth, SynthText, and SynthAdd and then evaluate the model on the ICDAR2015 dataset.

**Comment by deepseek** [comment]
@Bartzi 
Nevertheless, how can I train a text detection model?

**Comment by Bartzi** [comment]
This model is meant for text recognition, not detection. It should be possible to use it for text detection, but I can guarantee that it won't work for a real world scene text detection problem right out of the box. I've tried myself and failed...

**Comment by deepseek** [comment]
But will you release the detection training code?

**Comment by Bartzi** [comment]
Nope, since I don't have it anymore and it would take way too much time for me to adjust it to the current API. But if you really want to try, the current code should already be usable as a baseline, because you should not need to change the overall architecture of the network...

**Comment by deepseek** [comment]
:)
