### ISSUE TITLE
link to download SynAdd dataset.?

### ISSUE THREAD

**Issue by lynx97** [Bartzi/kiss#7]
I cannot register baidu account, so I am not able to download this dataset.
Could anyone who downloaded send me another link to download?
Thanks

**Comment by Bartzi** [comment]
:sweat_smile: I'd love to help you but I do not have another link to let you get the dataset...

**Comment by lynx97** [comment]
:( Could you upload it to google drive, one drive, or something like these? :dancing_men:

**Comment by Bartzi** [comment]
Nope, I don't think I'm allowed to do that... and also I do not have the storage capability for this. I was only able to download the data because a chinese colleague helped me. Maybe you could reach out to the original authors, who published the dataset?

**Comment by lynx97** [comment]
Thank you for your advise.
