### ISSUE TITLE
mjsynth.npz only has first letter of each word in "text"

### ISSUE THREAD

**Issue by daquilnp** [Bartzi/kiss#8]
I would like to start by saying I really enjoyed reading your paper and I am currently porting it to Pytorch. 

I was going through the steps to download the synth data (outlined on your github) and during the filter_word_length I noticed that the "text" array in mjsynth.npz  only contains the first letter of each word in the dataset. Is there a reason for this? Thank you.

**Comment by Bartzi** [comment]
Hi,

thanks for bringing this issue to my attention. I must have grabbed the wrong file :sweat_smile:. I've uploaded a fixed version of the `mjsynth.npz` annotation file.
Thanks also for porting the code to Pytorch :wink:.

**Comment by daquilnp** [comment]
Perfect, that fixed it :)
